### PR TITLE
chore(update): is-glob

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @es128 @phated i need some feedback on this update (tests failed) due `?` character. 

What we can do:
1. Modify https://github.com/es128/glob-parent/blob/master/index.js#L20 regexp for backward compatobility
2. Release major version and remove https://github.com/es128/glob-parent/blob/master/test.js#L50 and https://github.com/es128/glob-parent/blob/master/test.js#L55 tests

`?` is valid character for `windows`

### CODE REVIEW

**Comment by phated** [comment]
@evilebottnawi we are working on it. Sorry for the delay.

**Comment by paulmillr** [comment]
@evilebottnawi i removed it in the PR

**Comment by evilebottnawi** [comment]
@paulmillr thanks

**Comment by phated** [comment]
Closing in favor of #21

**Pull request closed without merging**
